version: '3'
services:
  nginx-static:
    image: nginx:latest
    ports:
      - "8091:80"
      - "8092:88"
    volumes:
      -  ./:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./resources:/etc/resources