version: '3'
services:
  nginx-web:
    image: nginx:latest
    ports:
      - "8093:80"
    volumes:
      - ~/projects/nginx-docker:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  nodeapp1:
    command: "npm run app"
    image: nodeapp
    build:
      context: ./nodeapp/
      dockerfile: Dockerfile
    container_name: nodeapp1

  nodeapp2:
    command: "npm run app"
    image: nodeapp
    build:
      context: ./nodeapp/
      dockerfile: Dockerfile
    container_name: nodeapp2

  nodeapp3:
    command: "npm run app"
    image: nodeapp
    build:
      context: ./nodeapp/
      dockerfile: Dockerfile
    container_name: nodeapp3

  nodeapp4:
    command: "npm run app"
    image: nodeapp
    build:
      context: ./nodeapp/
      dockerfile: Dockerfile
    container_name: nodeapp4